//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AzureAEDFinderWCFServiceWebRole
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class vtrescueEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new vtrescueEntities object using the connection string found in the 'vtrescueEntities' section of the application configuration file.
        /// </summary>
        public vtrescueEntities() : base("name=vtrescueEntities", "vtrescueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new vtrescueEntities object.
        /// </summary>
        public vtrescueEntities(string connectionString) : base(connectionString, "vtrescueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new vtrescueEntities object.
        /// </summary>
        public vtrescueEntities(EntityConnection connection) : base(connection, "vtrescueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aed> aeds
        {
            get
            {
                if ((_aeds == null))
                {
                    _aeds = base.CreateObjectSet<aed>("aeds");
                }
                return _aeds;
            }
        }
        private ObjectSet<aed> _aeds;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aeds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaeds(aed aed)
        {
            base.AddObject("aeds", aed);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="vtrescueModel", Name="aed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aed object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static aed Createaed(global::System.Int32 id)
        {
            aed aed = new aed();
            aed.ID = id;
            return aed;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private global::System.String _department;
        partial void OndepartmentChanging(global::System.String value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building
        {
            get
            {
                return _building;
            }
            set
            {
                OnbuildingChanging(value);
                ReportPropertyChanging("building");
                _building = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building");
                OnbuildingChanged();
            }
        }
        private global::System.String _building;
        partial void OnbuildingChanging(global::System.String value);
        partial void OnbuildingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> lat
        {
            get
            {
                return _lat;
            }
            set
            {
                OnlatChanging(value);
                ReportPropertyChanging("lat");
                _lat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lat");
                OnlatChanged();
            }
        }
        private Nullable<global::System.Double> _lat;
        partial void OnlatChanging(Nullable<global::System.Double> value);
        partial void OnlatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> @long
        {
            get
            {
                return _long;
            }
            set
            {
                OnlongChanging(value);
                ReportPropertyChanging("long");
                _long = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("long");
                OnlongChanged();
            }
        }
        private Nullable<global::System.Double> _long;
        partial void OnlongChanging(Nullable<global::System.Double> value);
        partial void OnlongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> floor
        {
            get
            {
                return _floor;
            }
            set
            {
                OnfloorChanging(value);
                ReportPropertyChanging("floor");
                _floor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("floor");
                OnfloorChanged();
            }
        }
        private Nullable<global::System.Byte> _floor;
        partial void OnfloorChanging(Nullable<global::System.Byte> value);
        partial void OnfloorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> pad_expiration
        {
            get
            {
                return _pad_expiration;
            }
            set
            {
                Onpad_expirationChanging(value);
                ReportPropertyChanging("pad_expiration");
                _pad_expiration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pad_expiration");
                Onpad_expirationChanged();
            }
        }
        private Nullable<global::System.DateTime> _pad_expiration;
        partial void Onpad_expirationChanging(Nullable<global::System.DateTime> value);
        partial void Onpad_expirationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loc_description
        {
            get
            {
                return _loc_description;
            }
            set
            {
                Onloc_descriptionChanging(value);
                ReportPropertyChanging("loc_description");
                _loc_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loc_description");
                Onloc_descriptionChanged();
            }
        }
        private global::System.String _loc_description;
        partial void Onloc_descriptionChanging(global::System.String value);
        partial void Onloc_descriptionChanged();

        #endregion
    
    }

    #endregion
    
}
