//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace VTRescuePhoneApp.AEDFinderServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinate", Namespace="http://schemas.datacontract.org/2004/07/AzureAEDFinderWCFServiceWebRole")]
    public partial class Coordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="building", Namespace="http://schemas.datacontract.org/2004/07/AzureAEDFinderWCFServiceWebRole", IsReference=true)]
    public partial class building : VTRescuePhoneApp.AEDFinderServiceReference.EntityObject {
        
        private int IDField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.AED))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.building))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.AED))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.building))]
    public partial class EntityObject : VTRescuePhoneApp.AEDFinderServiceReference.StructuralObject {
        
        private VTRescuePhoneApp.AEDFinderServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VTRescuePhoneApp.AEDFinderServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AED", Namespace="http://schemas.datacontract.org/2004/07/AzureAEDFinderWCFServiceWebRole", IsReference=true)]
    public partial class AED : VTRescuePhoneApp.AEDFinderServiceReference.EntityObject {
        
        private int IDField;
        
        private string SNField;
        
        private string buildingField;
        
        private string departmentField;
        
        private string loc_descriptionField;
        
        private System.DateTime pad_expirationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SN {
            get {
                return this.SNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNField, value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string building {
            get {
                return this.buildingField;
            }
            set {
                if ((object.ReferenceEquals(this.buildingField, value) != true)) {
                    this.buildingField = value;
                    this.RaisePropertyChanged("building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loc_description {
            get {
                return this.loc_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.loc_descriptionField, value) != true)) {
                    this.loc_descriptionField = value;
                    this.RaisePropertyChanged("loc_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime pad_expiration {
            get {
                return this.pad_expirationField;
            }
            set {
                if ((this.pad_expirationField.Equals(value) != true)) {
                    this.pad_expirationField = value;
                    this.RaisePropertyChanged("pad_expiration");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.EntityKeyMember> EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.building))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTRescuePhoneApp.AEDFinderServiceReference.AED))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AEDFinderServiceReference.AEDServiceInterface")]
    public interface AEDServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AEDServiceInterface/GetClosestBuildings", ReplyAction="http://tempuri.org/AEDServiceInterface/GetClosestBuildingsResponse")]
        System.IAsyncResult BeginGetClosestBuildings(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord, int numberOfBuidings, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> EndGetClosestBuildings(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AEDServiceInterface/GetWalkingDirections", ReplyAction="http://tempuri.org/AEDServiceInterface/GetWalkingDirectionsResponse")]
        System.IAsyncResult BeginGetWalkingDirections(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from, VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> EndGetWalkingDirections(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AEDServiceInterface/GetAEDsForBuilding", ReplyAction="http://tempuri.org/AEDServiceInterface/GetAEDsForBuildingResponse")]
        System.IAsyncResult BeginGetAEDsForBuilding(string building, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> EndGetAEDsForBuilding(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AEDServiceInterfaceChannel : VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClosestBuildingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClosestBuildingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWalkingDirectionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWalkingDirectionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAEDsForBuildingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAEDsForBuildingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AEDServiceInterfaceClient : System.ServiceModel.ClientBase<VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface>, VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface {
        
        private BeginOperationDelegate onBeginGetClosestBuildingsDelegate;
        
        private EndOperationDelegate onEndGetClosestBuildingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetClosestBuildingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWalkingDirectionsDelegate;
        
        private EndOperationDelegate onEndGetWalkingDirectionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetWalkingDirectionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAEDsForBuildingDelegate;
        
        private EndOperationDelegate onEndGetAEDsForBuildingDelegate;
        
        private System.Threading.SendOrPostCallback onGetAEDsForBuildingCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AEDServiceInterfaceClient() {
        }
        
        public AEDServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AEDServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AEDServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AEDServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetClosestBuildingsCompletedEventArgs> GetClosestBuildingsCompleted;
        
        public event System.EventHandler<GetWalkingDirectionsCompletedEventArgs> GetWalkingDirectionsCompleted;
        
        public event System.EventHandler<GetAEDsForBuildingCompletedEventArgs> GetAEDsForBuildingCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.BeginGetClosestBuildings(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord, int numberOfBuidings, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClosestBuildings(coord, numberOfBuidings, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.EndGetClosestBuildings(System.IAsyncResult result) {
            return base.Channel.EndGetClosestBuildings(result);
        }
        
        private System.IAsyncResult OnBeginGetClosestBuildings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord = ((VTRescuePhoneApp.AEDFinderServiceReference.Coordinate)(inValues[0]));
            int numberOfBuidings = ((int)(inValues[1]));
            return ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).BeginGetClosestBuildings(coord, numberOfBuidings, callback, asyncState);
        }
        
        private object[] OnEndGetClosestBuildings(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> retVal = ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).EndGetClosestBuildings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClosestBuildingsCompleted(object state) {
            if ((this.GetClosestBuildingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClosestBuildingsCompleted(this, new GetClosestBuildingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClosestBuildingsAsync(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord, int numberOfBuidings) {
            this.GetClosestBuildingsAsync(coord, numberOfBuidings, null);
        }
        
        public void GetClosestBuildingsAsync(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord, int numberOfBuidings, object userState) {
            if ((this.onBeginGetClosestBuildingsDelegate == null)) {
                this.onBeginGetClosestBuildingsDelegate = new BeginOperationDelegate(this.OnBeginGetClosestBuildings);
            }
            if ((this.onEndGetClosestBuildingsDelegate == null)) {
                this.onEndGetClosestBuildingsDelegate = new EndOperationDelegate(this.OnEndGetClosestBuildings);
            }
            if ((this.onGetClosestBuildingsCompletedDelegate == null)) {
                this.onGetClosestBuildingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClosestBuildingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetClosestBuildingsDelegate, new object[] {
                        coord,
                        numberOfBuidings}, this.onEndGetClosestBuildingsDelegate, this.onGetClosestBuildingsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.BeginGetWalkingDirections(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from, VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWalkingDirections(from, to, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.EndGetWalkingDirections(System.IAsyncResult result) {
            return base.Channel.EndGetWalkingDirections(result);
        }
        
        private System.IAsyncResult OnBeginGetWalkingDirections(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from = ((VTRescuePhoneApp.AEDFinderServiceReference.Coordinate)(inValues[0]));
            VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to = ((VTRescuePhoneApp.AEDFinderServiceReference.Coordinate)(inValues[1]));
            return ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).BeginGetWalkingDirections(from, to, callback, asyncState);
        }
        
        private object[] OnEndGetWalkingDirections(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> retVal = ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).EndGetWalkingDirections(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWalkingDirectionsCompleted(object state) {
            if ((this.GetWalkingDirectionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWalkingDirectionsCompleted(this, new GetWalkingDirectionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWalkingDirectionsAsync(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from, VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to) {
            this.GetWalkingDirectionsAsync(from, to, null);
        }
        
        public void GetWalkingDirectionsAsync(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from, VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to, object userState) {
            if ((this.onBeginGetWalkingDirectionsDelegate == null)) {
                this.onBeginGetWalkingDirectionsDelegate = new BeginOperationDelegate(this.OnBeginGetWalkingDirections);
            }
            if ((this.onEndGetWalkingDirectionsDelegate == null)) {
                this.onEndGetWalkingDirectionsDelegate = new EndOperationDelegate(this.OnEndGetWalkingDirections);
            }
            if ((this.onGetWalkingDirectionsCompletedDelegate == null)) {
                this.onGetWalkingDirectionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWalkingDirectionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetWalkingDirectionsDelegate, new object[] {
                        from,
                        to}, this.onEndGetWalkingDirectionsDelegate, this.onGetWalkingDirectionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.BeginGetAEDsForBuilding(string building, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAEDsForBuilding(building, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface.EndGetAEDsForBuilding(System.IAsyncResult result) {
            return base.Channel.EndGetAEDsForBuilding(result);
        }
        
        private System.IAsyncResult OnBeginGetAEDsForBuilding(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string building = ((string)(inValues[0]));
            return ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).BeginGetAEDsForBuilding(building, callback, asyncState);
        }
        
        private object[] OnEndGetAEDsForBuilding(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> retVal = ((VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface)(this)).EndGetAEDsForBuilding(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAEDsForBuildingCompleted(object state) {
            if ((this.GetAEDsForBuildingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAEDsForBuildingCompleted(this, new GetAEDsForBuildingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAEDsForBuildingAsync(string building) {
            this.GetAEDsForBuildingAsync(building, null);
        }
        
        public void GetAEDsForBuildingAsync(string building, object userState) {
            if ((this.onBeginGetAEDsForBuildingDelegate == null)) {
                this.onBeginGetAEDsForBuildingDelegate = new BeginOperationDelegate(this.OnBeginGetAEDsForBuilding);
            }
            if ((this.onEndGetAEDsForBuildingDelegate == null)) {
                this.onEndGetAEDsForBuildingDelegate = new EndOperationDelegate(this.OnEndGetAEDsForBuilding);
            }
            if ((this.onGetAEDsForBuildingCompletedDelegate == null)) {
                this.onGetAEDsForBuildingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAEDsForBuildingCompleted);
            }
            base.InvokeAsync(this.onBeginGetAEDsForBuildingDelegate, new object[] {
                        building}, this.onEndGetAEDsForBuildingDelegate, this.onGetAEDsForBuildingCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface CreateChannel() {
            return new AEDServiceInterfaceClientChannel(this);
        }
        
        private class AEDServiceInterfaceClientChannel : ChannelBase<VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface>, VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface {
            
            public AEDServiceInterfaceClientChannel(System.ServiceModel.ClientBase<VTRescuePhoneApp.AEDFinderServiceReference.AEDServiceInterface> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetClosestBuildings(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate coord, int numberOfBuidings, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = coord;
                _args[1] = numberOfBuidings;
                System.IAsyncResult _result = base.BeginInvoke("GetClosestBuildings", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> EndGetClosestBuildings(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building> _result = ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.building>)(base.EndInvoke("GetClosestBuildings", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWalkingDirections(VTRescuePhoneApp.AEDFinderServiceReference.Coordinate from, VTRescuePhoneApp.AEDFinderServiceReference.Coordinate to, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = from;
                _args[1] = to;
                System.IAsyncResult _result = base.BeginInvoke("GetWalkingDirections", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> EndGetWalkingDirections(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate> _result = ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.Coordinate>)(base.EndInvoke("GetWalkingDirections", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAEDsForBuilding(string building, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = building;
                System.IAsyncResult _result = base.BeginInvoke("GetAEDsForBuilding", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> EndGetAEDsForBuilding(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED> _result = ((System.Collections.ObjectModel.ObservableCollection<VTRescuePhoneApp.AEDFinderServiceReference.AED>)(base.EndInvoke("GetAEDsForBuilding", _args, result)));
                return _result;
            }
        }
    }
}
